### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by Zwirled** [Zwirled/plate-mate#2]

**Comment by HarryUnderscore13** [comment]
## Completed desktop;
Landing page,
Recipe feed,
Saved Plates

**Comment by HarryUnderscore13** [comment]
## Completed Desktop & Mobile;
Landing/Home page,
Recipe feed,
Saved Plates

## To do;
Shopping list,
Recipe page,

**Comment by seacrest3** [comment]
Got compilation error when running the code.
